Fix packaging
getindata/flink-sql-emr-runner pull request #18
Opened 2023-03-02 14:36 UTC by grzegorz8

2023-03-02 14:57 UTC, andrzejdackiewicz commented on tests/test_s3.py
> +from flink_sql_runner.s3 import get_latest_object  # noqa: E402
Skoro już nie robimy sys.path.insert ... to mozna #noqa: E402 usunąć :)

2023-03-02 15:00 UTC, andrzejdackiewicz requested changes

2023-03-02 15:00 UTC, andrzejdackiewicz commented on tests/test_deploy_job.py
> +from flink_sql_runner.deploy_job import EmrJobRunner  # noqa: 402
We can remove # noqa: 402

2023-03-02 15:00 UTC, andrzejdackiewicz commented on tests/test_s3.py
> +from flink_sql_runner.s3 import get_latest_object  # noqa: E402
Since we no longer perform sys.path.insert then we can remove #noqa: E402 :)

2023-03-02 15:05 UTC, grzegorz8 commented on tests/test_s3.py
> +from flink_sql_runner.s3 import get_latest_object  # noqa: E402
done

2023-03-02 15:05 UTC, grzegorz8 commented on tests/test_deploy_job.py
> +from flink_sql_runner.deploy_job import EmrJobRunner  # noqa: 402
done

2023-03-07 08:21 UTC, moss2k13 approved these changes

2023-03-07 08:29 UTC, andrzejdackiewicz approved these changes
LGTM :)

2023-03-07 08:29 UTC, merged